dag:
  conf:
    task_parallelism: 1
    scheduler_party_id: '20008'
  parties:
  - party_id:
    - '20008'
    role: guest
  - party_id:
    - '10008'
    role: host
  - party_id:
    - '10008'
    role: arbiter
  party_tasks:
    guest_20008:
      conf:
        test_reader_guest: 2
      parties:
      - party_id:
        - '20008'
        role: guest
      tasks:
        reader_0:
          inputs:
            parameters:
              path: eggroll:///db/guest001
              format: raw_table
    host_10008:
      conf:
        test_reader_guest: 2
      parties:
      - party_id:
        - '10008'
        role: host
      tasks:
        reader_0:
          inputs:
            parameters:
              path: eggroll:///db/host001
              format: raw_table
  stage: train
  tasks:
    evaluation_0:
      component_ref: evaluation
      dependent_tasks:
      - lr_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: lr_0
              roles:
              - guest
      parties:
      - party_id:
        - '20008'
        role: guest
      stage: default
    intersection_0:
      component_ref: intersection
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
        parameters:
          method: raw
      parties:
      - party_id:
        - '20008'
        role: guest
      - party_id:
        - '10008'
        role: host
      stage: default
    intersection_1:
      component_ref: intersection
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
        parameters:
          method: raw
      parties:
      - party_id:
        - '20008'
        role: guest
      - party_id:
        - '10008'
        role: host
      stage: default
    lr_0:
      component_ref: hetero_lr
      dependent_tasks:
      - intersection_0
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: intersection_0
              roles:
              - guest
              - host
          validate_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: intersection_0
              roles:
              - guest
              - host
        parameters:
          batch_size: 100
          learning_rate: 0.01
          max_iter: 1
    reader_0:
      component_ref: reader
      parties:
      - party_id:
        - '20008'
        role: guest
      - party_id:
        - '10008'
        role: host
      stage: default
schema_version: 2.0.0.alpha
